### ISSUE TITLE
Missing asset “

### ISSUE THREAD

**Issue by blainesolomon** [CodeSlicing/pure-swift-ui-design#1]
Missing PNG `To demonstrate some of the advantages, let's say you want to generate the following label:`

Linked to https://github.com/CodeSlicing/pure-swift-ui-design/blob/feature/1.0.0/Assets/Images/modifier-example-label.png

**Comment by CodeSlicing** [comment]
Thanks, yes the readme is still a work in progress. Will be updated properly for the final release 👍🏻

**Comment by blainesolomon** [comment]
❤️🤘
